#ifndef ACTIVECHAIN_VERIFIER_H
#define ACTIVECHAIN_VERIFIER_H

/* Generated by activechain-apple-distribution. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define ACTIVECHAIN_VERIFY_OK 0

#define ACTIVECHAIN_VERIFY_TOO_LARGE 1

#define ACTIVECHAIN_VERIFY_DECODE_ERROR 2

#define ACTIVECHAIN_VERIFY_TYPE_MISMATCH 3

#define ACTIVECHAIN_VERIFY_VERSION_MISMATCH 4

#define ACTIVECHAIN_VERIFY_COMMITMENT_MISMATCH 5

#define ACTIVECHAIN_VERIFY_NULL_POINTER 6

#define ACTIVECHAIN_VERIFY_RELATION_MISMATCH 7

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

uint32_t activechain_verifier_abi_revision(void);

uint32_t activechain_verifier_schema_revision(void);

uint64_t activechain_verifier_protocol_revision(void);

/**
 * # Safety
 * For lengths through [`activechain_verifier_api::MAX_ENVELOPE_LENGTH`], the caller must provide a
 * readable `bytes` buffer of `bytes_len` bytes, or a null pointer only when `bytes_len` is zero.
 * Oversized inputs are rejected before the pointer is materialized. The verifier does not retain
 * or write through the pointer.
 */
uint32_t activechain_inspect_envelope_code(const uint8_t *bytes,
                                           uint32_t bytes_len,
                                           uint16_t expected_type,
                                           uint16_t expected_version);

/**
 * # Safety
 * For lengths through [`activechain_verifier_api::MAX_ENVELOPE_LENGTH`], the caller must provide a
 * readable `bytes` buffer of `bytes_len` bytes. The verifier does not retain or write through it.
 */
uint32_t activechain_verify_principal_code(const uint8_t *bytes, uint32_t bytes_len);

/**
 * # Safety
 * The caller must provide a readable `bytes` buffer of `bytes_len` bytes. No pointer is retained.
 */
uint32_t activechain_verify_capability_code(const uint8_t *bytes, uint32_t bytes_len);

/**
 * # Safety
 * The caller must provide readable parent and child buffers for the declared lengths. No pointer
 * is retained, and oversized combined input is rejected before either pointer is materialized.
 */
uint32_t activechain_verify_capability_attenuation_code(const uint8_t *parent,
                                                        uint32_t parent_len,
                                                        const uint8_t *child,
                                                        uint32_t child_len);

/**
 * # Safety
 * The caller must provide a readable canonical authorization-chain buffer. No pointer is retained.
 */
uint32_t activechain_verify_authorization_chain_code(const uint8_t *bytes, uint32_t bytes_len);

/**
 * # Safety
 * The caller must provide a readable `bytes` buffer of `bytes_len` bytes. No pointer is retained.
 */
uint32_t activechain_verify_policy_decision_code(const uint8_t *bytes, uint32_t bytes_len);

/**
 * # Safety
 * The caller must provide readable buffers for all declared lengths. No pointer is retained.
 */
uint32_t activechain_verify_state_membership_code(const uint8_t *commitment,
                                                  uint32_t commitment_len,
                                                  const uint8_t *object,
                                                  uint32_t object_len,
                                                  const uint8_t *proof,
                                                  uint32_t proof_len);

/**
 * # Safety
 * The caller must provide readable commitment/proof buffers and a readable 48-byte object ID.
 */
uint32_t activechain_verify_state_non_membership_code(const uint8_t *commitment,
                                                      uint32_t commitment_len,
                                                      const uint8_t *object_id,
                                                      const uint8_t *proof,
                                                      uint32_t proof_len);

/**
 * # Safety
 * The caller must provide a readable canonical finality-bundle buffer. No pointer is retained.
 */
uint32_t activechain_verify_finality_bundle_code(const uint8_t *bytes, uint32_t bytes_len);

/**
 * # Safety
 * The caller must provide readable canonical finality and receipt buffers for the declared
 * lengths. Null pointers are permitted only for zero-length buffers. No pointer is retained.
 */
uint32_t activechain_verify_block_receipt_code(const uint8_t *finality,
                                               uint32_t finality_len,
                                               const uint8_t *receipt,
                                               uint32_t receipt_len);

/**
 * # Safety
 * The caller must provide readable buffers for the declared lengths and a readable 48-byte digest.
 * Null pointers are permitted only for zero-length buffers and no pointer is retained.
 */
uint32_t activechain_verify_commitment_code(const uint8_t *domain,
                                            uint32_t domain_len,
                                            const uint8_t *body,
                                            uint32_t body_len,
                                            const uint8_t *expected_digest);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ACTIVECHAIN_VERIFIER_H */
