#ifndef ACTIVECHAIN_VERIFIER_H
#define ACTIVECHAIN_VERIFIER_H

/* Generated by activechain-apple-distribution. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define ACTIVECHAIN_VERIFY_OK 0

#define ACTIVECHAIN_VERIFY_TOO_LARGE 1

#define ACTIVECHAIN_VERIFY_DECODE_ERROR 2

#define ACTIVECHAIN_VERIFY_TYPE_MISMATCH 3

#define ACTIVECHAIN_VERIFY_VERSION_MISMATCH 4

#define ACTIVECHAIN_VERIFY_COMMITMENT_MISMATCH 5

#define ACTIVECHAIN_VERIFY_NULL_POINTER 6

#define ACTIVECHAIN_VERIFY_RELATION_MISMATCH 7

#define ACTIVECHAIN_VERIFY_BUFFER_TOO_SMALL 8

#define ACTIVECHAIN_VERIFY_DETAIL_NONE 0

#define ACTIVECHAIN_VERIFY_DETAIL_UNEXPECTED_END 1

#define ACTIVECHAIN_VERIFY_DETAIL_NON_MINIMAL_LENGTH 2

#define ACTIVECHAIN_VERIFY_DETAIL_LENGTH_OVERFLOW 3

#define ACTIVECHAIN_VERIFY_DETAIL_LENGTH_LIMIT 4

#define ACTIVECHAIN_VERIFY_DETAIL_INVALID_BOOLEAN 5

#define ACTIVECHAIN_VERIFY_DETAIL_INVALID_ENUM 6

#define ACTIVECHAIN_VERIFY_DETAIL_INVALID_VALUE 7

#define ACTIVECHAIN_VERIFY_DETAIL_TRAILING_DATA 8

#define ACTIVECHAIN_ANCHOR_RESPONSE_SUBMISSION 1

#define ACTIVECHAIN_ANCHOR_RESPONSE_RECORD 2

#define ACTIVECHAIN_ANCHOR_RESPONSE_RPC_ERROR 3

#define ACTIVECHAIN_ANCHOR_STATUS_NONE 0

#define ACTIVECHAIN_ANCHOR_STATUS_PENDING 1

#define ACTIVECHAIN_ANCHOR_STATUS_FINALIZED 2

#define ACTIVECHAIN_ANCHOR_STATUS_REJECTED 3

typedef struct ActivechainAnchorResult {
  uint32_t code;
  uint32_t response_kind;
  uint32_t anchor_status;
  uint32_t rpc_error;
  uint32_t required_output_length;
  uint8_t reference[48];
} ActivechainAnchorResult;

typedef struct ActivechainVerifierResult {
  uint32_t code;
  uint32_t detail;
  uint32_t offset;
  uint32_t required_body_length;
  uint16_t type_tag;
  uint16_t schema_version;
  uint8_t canonical_value_commitment[48];
} ActivechainVerifierResult;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Constructs a canonical digest-anchor statement and its deterministic 48-byte reference.
 *
 * A null `output` with zero capacity performs a size query. No pointer is retained.
 *
 * # Safety
 * The domain and digest must be readable for their declared fixed/bounded lengths, `reference`
 * and `required_output_length` must be writable, and non-null output must be writable for its
 * declared capacity. Input and output regions must not overlap.
 */
uint32_t activechain_anchor_statement_v1(const uint8_t *application_domain,
                                         uint32_t application_domain_len,
                                         const uint8_t *digest,
                                         uint8_t *output,
                                         uint32_t output_capacity,
                                         uint32_t *required_output_length,
                                         uint8_t *reference);

/**
 * Encodes a canonical submit-anchor RPC request from an already canonical statement envelope.
 *
 * # Safety
 * The statement must be readable, and output/result pointers follow the size-query contract of
 * `activechain_anchor_statement_v1`. No pointer is retained.
 */
uint32_t activechain_anchor_submit_request_v1(const uint8_t *statement,
                                              uint32_t statement_len,
                                              uint8_t *output,
                                              uint32_t output_capacity,
                                              uint32_t *required_output_length);

/**
 * Encodes a canonical resolve-anchor RPC request for an exact 48-byte reference.
 *
 * # Safety
 * `reference` must be readable for 48 bytes; output/result pointers follow the size-query
 * contract of `activechain_anchor_statement_v1`. No pointer is retained.
 */
uint32_t activechain_anchor_resolve_request_v1(const uint8_t *reference,
                                               uint8_t *output,
                                               uint32_t output_capacity,
                                               uint32_t *required_output_length);

/**
 * Decodes a bounded canonical RPC response. For finalized records, output is the canonical
 * `AnchorFinalizedEvidenceV1` envelope; pending/rejected/submission/error responses have no output.
 *
 * # Safety
 * The response must be readable. `result` must be writable, and output follows the size-query
 * contract above. No pointer is retained.
 */
uint32_t activechain_anchor_decode_response_v1(const uint8_t *response,
                                               uint32_t response_len,
                                               uint8_t *output,
                                               uint32_t output_capacity,
                                               struct ActivechainAnchorResult *result);

uint32_t activechain_verifier_abi_revision(void);

uint32_t activechain_verifier_schema_revision(void);

uint64_t activechain_verifier_protocol_revision(void);

/**
 * Inspects one bounded canonical envelope and returns its exact body and canonical commitment.
 *
 * A null `body_output` with zero capacity is a size query. The result descriptor is populated on
 * every path for which it is non-null. No pointer is retained.
 *
 * # Safety
 * `result` must be writable. For accepted lengths, `bytes` must be readable unless length is zero.
 * `body_output` must be writable for `body_capacity` bytes unless capacity is zero. The result,
 * input, and output regions must not overlap.
 */
uint32_t activechain_verify_envelope_v1(const uint8_t *bytes,
                                        uint32_t bytes_len,
                                        uint16_t expected_type,
                                        uint16_t expected_version,
                                        uint8_t *body_output,
                                        uint32_t body_capacity,
                                        struct ActivechainVerifierResult *result);

/**
 * # Safety
 * For lengths through [`activechain_verifier_api::MAX_ENVELOPE_LENGTH`], the caller must provide a
 * readable `bytes` buffer of `bytes_len` bytes, or a null pointer only when `bytes_len` is zero.
 * Oversized inputs are rejected before the pointer is materialized. The verifier does not retain
 * or write through the pointer.
 */
uint32_t activechain_inspect_envelope_code(const uint8_t *bytes,
                                           uint32_t bytes_len,
                                           uint16_t expected_type,
                                           uint16_t expected_version);

/**
 * # Safety
 * For lengths through [`activechain_verifier_api::MAX_ENVELOPE_LENGTH`], the caller must provide a
 * readable `bytes` buffer of `bytes_len` bytes. The verifier does not retain or write through it.
 */
uint32_t activechain_verify_principal_code(const uint8_t *bytes, uint32_t bytes_len);

/**
 * # Safety
 * The caller must provide a readable `bytes` buffer of `bytes_len` bytes. No pointer is retained.
 */
uint32_t activechain_verify_capability_code(const uint8_t *bytes, uint32_t bytes_len);

/**
 * # Safety
 * The caller must provide readable parent and child buffers for the declared lengths. No pointer
 * is retained, and oversized combined input is rejected before either pointer is materialized.
 */
uint32_t activechain_verify_capability_attenuation_code(const uint8_t *parent,
                                                        uint32_t parent_len,
                                                        const uint8_t *child,
                                                        uint32_t child_len);

/**
 * # Safety
 * The caller must provide a readable canonical authorization-chain buffer. No pointer is retained.
 */
uint32_t activechain_verify_authorization_chain_code(const uint8_t *bytes, uint32_t bytes_len);

/**
 * Verifies actor and capability signatures against controller keys proven in finalized state.
 * `trusted_genesis` points to exactly 48 readable bytes.
 */
uint32_t activechain_verify_signed_authorization_chain_code(const uint8_t *bytes,
                                                            uint32_t bytes_len,
                                                            const uint8_t *finality,
                                                            uint32_t finality_len,
                                                            const uint8_t *trusted_genesis);

/**
 * Verifies a principal state object, its finalized membership proof, and one active authenticator.
 * `trusted_genesis`, `expected_principal`, and `expected_authenticator` each point to 48 bytes.
 * `expected_purpose` uses the canonical AuthenticatorPurpose tag (0 through 5).
 */
uint32_t activechain_verify_finalized_principal_authenticator_code(
    const uint8_t *principal_object,
    uint32_t principal_object_len,
    const uint8_t *principal_proof,
    uint32_t principal_proof_len,
    const uint8_t *authenticator_set,
    uint32_t authenticator_set_len,
    const uint8_t *finality,
    uint32_t finality_len,
    const uint8_t *trusted_genesis,
    const uint8_t *expected_principal,
    const uint8_t *expected_authenticator,
    uint8_t expected_purpose);

/**
 * # Safety
 * The caller must provide a readable `bytes` buffer of `bytes_len` bytes. No pointer is retained.
 */
uint32_t activechain_verify_policy_decision_code(const uint8_t *bytes, uint32_t bytes_len);

/**
 * # Safety
 * The caller must provide readable buffers for all declared lengths. No pointer is retained.
 */
uint32_t activechain_verify_state_membership_code(const uint8_t *commitment,
                                                  uint32_t commitment_len,
                                                  const uint8_t *object,
                                                  uint32_t object_len,
                                                  const uint8_t *proof,
                                                  uint32_t proof_len);

/**
 * # Safety
 * The caller must provide readable commitment/proof buffers and a readable 48-byte object ID.
 */
uint32_t activechain_verify_state_non_membership_code(const uint8_t *commitment,
                                                      uint32_t commitment_len,
                                                      const uint8_t *object_id,
                                                      const uint8_t *proof,
                                                      uint32_t proof_len);

/**
 * # Safety
 * The caller must provide a readable canonical finality-bundle buffer. No pointer is retained.
 */
uint32_t activechain_verify_finality_bundle_code(const uint8_t *bytes, uint32_t bytes_len);

/**
 * # Safety
 * The caller must provide readable canonical finality and receipt buffers for the declared
 * lengths. Null pointers are permitted only for zero-length buffers. No pointer is retained.
 */
uint32_t activechain_verify_block_receipt_code(const uint8_t *finality,
                                               uint32_t finality_len,
                                               const uint8_t *receipt,
                                               uint32_t receipt_len);

/**
 * Verifies canonical finalized anchor evidence against explicit trusted network parameters.
 *
 * # Safety
 * Evidence and statement buffers must be readable for their declared lengths. `chain_id` and
 * `genesis` must each point to readable 48-byte values. No pointer is retained.
 */
uint32_t activechain_verify_anchor_finalized_evidence_code(const uint8_t *evidence,
                                                           uint32_t evidence_len,
                                                           const uint8_t *statement,
                                                           uint32_t statement_len,
                                                           const uint8_t *chain_id,
                                                           const uint8_t *genesis,
                                                           uint64_t protocol_revision,
                                                           uint32_t verifier_revision);

/**
 * # Safety
 * The caller must provide readable buffers for the declared lengths and a readable 48-byte digest.
 * Null pointers are permitted only for zero-length buffers and no pointer is retained.
 */
uint32_t activechain_verify_commitment_code(const uint8_t *domain,
                                            uint32_t domain_len,
                                            const uint8_t *body,
                                            uint32_t body_len,
                                            const uint8_t *expected_digest);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ACTIVECHAIN_VERIFIER_H */
