//! Generates the frozen development vectors from typed protocol values.

use activechain_canonical_codec::{CanonicalType, encode_body, encode_envelope};
use activechain_capability::verify_attenuation;
use activechain_object::{ObjectTransitionError, transfer_object};
use activechain_policy_kernel::{
    APL_LANGUAGE_VERSION, ActorBinding, ApprovalFact, DecisionResult, PolicyDecision, PolicyEffect,
    PolicyObligation, PolicyPredicate, PolicyRequest, PolicyRequestFields, PolicyRule, PolicySet,
    combine_effects, evaluate,
};
use activechain_principal::{
    LifecycleAuthorization, PrincipalCommand, PrincipalGenesis, apply_lifecycle_command,
    create_principal,
};
use activechain_protocol_commitment::{DomainTag, commit};
use activechain_protocol_types::{
    AccessManifest, AccessManifestFields, ActionId, AuthenticatorDescriptor, AuthenticatorId,
    AuthenticatorPurpose, BoundedActionSet, CapabilityGrant, CapabilityGrantFields, CapabilityId,
    CryptoSuiteId, DataSelector, Digest384, FreezeState, HolderBinding, Object, ObjectFields,
    ObjectFlags, ObjectId, ObjectOwner, ObjectVersionRef, Principal, PrincipalId, PrincipalKind,
    ProtocolSignature, RateLimit, RecoveryRequest, ResourceSelector,
};
use activechain_transition::{
    ObjectState, ReceiptResult, TRANSFER_OBJECT_ACTION_ID, TransferCommand, TransferTransaction,
    TransitionReceipt, apply_transfer_transaction,
};

fn repeated_digest(byte: u8) -> Digest384 {
    Digest384::new([byte; 48])
}

fn principal_v1() -> Principal {
    Principal::new(
        PrincipalId::new(repeated_digest(0x11)),
        PrincipalKind::Agent,
        repeated_digest(0x22),
        repeated_digest(0x33),
        repeated_digest(0x44),
        7,
        FreezeState::Active,
        repeated_digest(0x55),
        1_000,
        42,
        43,
    )
    .expect("the source vector must satisfy the Principal v1 schema")
}

fn hexadecimal(bytes: &[u8]) -> String {
    const DIGITS: &[u8; 16] = b"0123456789abcdef";

    let mut output = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        output.push(char::from(DIGITS[usize::from(byte >> 4)]));
        output.push(char::from(DIGITS[usize::from(byte & 0x0f)]));
    }
    output
}

fn render_principal_v1() -> String {
    let principal = principal_v1();
    let body = encode_body(&principal).expect("Principal v1 body must fit its declared bound");
    let envelope =
        encode_envelope(&principal).expect("Principal v1 envelope must fit its declared bound");
    let commitment = commit(DomainTag::CANONICAL_VALUE, &principal)
        .expect("Principal v1 commitment input must encode");

    format!(
        "# ActiveChain canonical vector\n\
# Generated by: cargo run --locked --quiet -p activechain-vector-generator\n\
# Transcript: P-001 draft 0.1\n\
\n\
vector=principal-v1\n\
type_tag=0x{:04x}\n\
schema_version={}\n\
\n\
principal_id=11 repeated 48 times\n\
principal_kind=Agent (4)\n\
controller_policy_hash=22 repeated 48 times\n\
recovery_policy_hash=33 repeated 48 times\n\
authenticator_set_root=44 repeated 48 times\n\
sequence=7\n\
freeze_state=Active (0)\n\
metadata_commitment=55 repeated 48 times\n\
anchor_deposit=1000\n\
created_at=42\n\
last_updated_at=43\n\
\n\
body_length={}\n\
body_hex={}\n\
envelope_hex={}\n\
commitment_domain=canonical-value (0x0001)\n\
canonical_value_commitment_hex={}\n",
        Principal::TYPE_TAG,
        Principal::SCHEMA_VERSION,
        body.len(),
        hexadecimal(&body),
        hexadecimal(&envelope),
        hexadecimal(commitment.as_bytes())
    )
}

fn identifier_principal(byte: u8) -> PrincipalId {
    PrincipalId::new(repeated_digest(byte))
}

fn identifier_capability(byte: u8) -> CapabilityId {
    CapabilityId::new(repeated_digest(byte))
}

fn identifier_action(byte: u8) -> ActionId {
    ActionId::new(repeated_digest(byte))
}

fn encoded_value<T: CanonicalType>(name: &str, value: &T) -> String {
    let body = encode_body(value).expect("vector body must fit its declared bound");
    let envelope = encode_envelope(value).expect("vector envelope must fit its declared bound");
    let commitment =
        commit(DomainTag::CANONICAL_VALUE, value).expect("vector commitment input must encode");
    format!(
        "{name}_type_tag=0x{:04x}\n\
{name}_schema_version={}\n\
{name}_body_length={}\n\
{name}_body_hex={}\n\
{name}_envelope_hex={}\n\
{name}_canonical_value_commitment_hex={}\n",
        T::TYPE_TAG,
        T::SCHEMA_VERSION,
        body.len(),
        hexadecimal(&body),
        hexadecimal(&envelope),
        hexadecimal(commitment.as_bytes()),
    )
}

fn authority_authenticator() -> AuthenticatorDescriptor {
    AuthenticatorDescriptor::new(
        AuthenticatorId::new(repeated_digest(0x66)),
        CryptoSuiteId::ML_DSA_65,
        vec![0x77; 1_952],
        AuthenticatorPurpose::Control,
        42,
        Some(1_000),
        None,
    )
    .expect("authority vector authenticator is valid")
}

fn authority_lifecycle() -> (Principal, Principal, Principal, RecoveryRequest) {
    let genesis = PrincipalGenesis {
        principal_id: identifier_principal(0x11),
        principal_kind: PrincipalKind::Agent,
        controller_policy_hash: repeated_digest(0x22),
        recovery_policy_hash: repeated_digest(0x33),
        authenticator_set_root: repeated_digest(0x44),
        metadata_commitment: repeated_digest(0x55),
        anchor_deposit: 1_000,
    };
    let created = create_principal(genesis, 42, 500).expect("authority genesis is valid");

    let controller = LifecycleAuthorization::controller(
        created.principal_id(),
        created.sequence(),
        created.controller_policy_hash(),
    );
    let rotation_output = apply_lifecycle_command(
        &created,
        PrincipalCommand::RotateController {
            expected_sequence: 0,
            new_controller_policy_hash: repeated_digest(0x23),
            new_authenticator_set_root: repeated_digest(0x45),
        },
        Some(&controller),
        43,
    )
    .expect("authority rotation is valid");
    let rotated = rotation_output.principal();
    assert_eq!(rotation_output.recovery_request(), None);

    let controller = LifecycleAuthorization::controller(
        rotated.principal_id(),
        rotated.sequence(),
        rotated.controller_policy_hash(),
    );
    let freeze_output = apply_lifecycle_command(
        &rotated,
        PrincipalCommand::Freeze { expected_sequence: 1 },
        Some(&controller),
        44,
    )
    .expect("authority freeze is valid");
    let frozen = freeze_output.principal();
    assert_eq!(freeze_output.recovery_request(), None);

    let recovery = LifecycleAuthorization::recovery(
        frozen.principal_id(),
        frozen.sequence(),
        frozen.recovery_policy_hash(),
    );
    let recovery_output = apply_lifecycle_command(
        &frozen,
        PrincipalCommand::InitiateRecovery {
            expected_sequence: 2,
            proposed_controller_policy_hash: repeated_digest(0x24),
            proposed_authenticator_set_root: repeated_digest(0x46),
            recovery_evidence_commitment: repeated_digest(0x88),
            challenge_deadline: 55,
            recovery_bond: 250,
        },
        Some(&recovery),
        45,
    )
    .expect("authority recovery initiation is valid");
    let pending = recovery_output.principal();
    let request = recovery_output.recovery_request().expect("recovery vector must produce request");

    (created, rotated, pending, request)
}

fn authority_signature(byte: u8) -> ProtocolSignature {
    ProtocolSignature::new(CryptoSuiteId::ML_DSA_44, vec![byte; 2_420])
        .expect("authority vector signature has canonical structure")
}

fn authority_capabilities() -> (CapabilityGrant, CapabilityGrant) {
    let revocation_registry = ObjectId::new(repeated_digest(0x93));
    let constraint_hash = repeated_digest(0x94);
    let parent = CapabilityGrant::new(
        CapabilityGrantFields {
            capability_id: identifier_capability(0x90),
            issuer: identifier_principal(0x91),
            holder_binding: HolderBinding::Principal(identifier_principal(0x92)),
            parent_capability: None,
            permitted_actions: BoundedActionSet::new(vec![
                identifier_action(0x01),
                identifier_action(0x02),
            ])
            .expect("authority vector actions are sorted"),
            resource_scope: ResourceSelector::ANY,
            data_scope: DataSelector::ANY,
            monetary_limit: Some(1_000),
            compute_limit: Some(10_000),
            rate_limit: Some(RateLimit::new(100, 50).expect("non-zero rate")),
            use_limit: Some(500),
            valid_from: 10,
            valid_until: Some(1_000),
            delegation_depth_remaining: 2,
            delegation_allowed: true,
            revocation_registry: Some(revocation_registry),
            constraint_hash,
        },
        authority_signature(0x95),
    )
    .expect("authority parent grant is valid");

    let child = CapabilityGrant::new(
        CapabilityGrantFields {
            capability_id: identifier_capability(0x96),
            issuer: identifier_principal(0x92),
            holder_binding: HolderBinding::Principal(identifier_principal(0x97)),
            parent_capability: Some(identifier_capability(0x90)),
            permitted_actions: BoundedActionSet::new(vec![identifier_action(0x01)])
                .expect("authority vector child action is valid"),
            resource_scope: ResourceSelector::exact(ObjectId::new(repeated_digest(0x98))),
            data_scope: DataSelector::exact(repeated_digest(0x99)),
            monetary_limit: Some(500),
            compute_limit: Some(5_000),
            rate_limit: Some(RateLimit::new(50, 50).expect("non-zero rate")),
            use_limit: Some(100),
            valid_from: 20,
            valid_until: Some(900),
            delegation_depth_remaining: 1,
            delegation_allowed: true,
            revocation_registry: Some(revocation_registry),
            constraint_hash,
        },
        authority_signature(0x9a),
    )
    .expect("authority child grant is valid");
    verify_attenuation(&parent, &child).expect("authority child is mechanically attenuated");
    (parent, child)
}

fn render_authority_v1() -> String {
    let authenticator = authority_authenticator();
    let (created, rotated, pending, recovery_request) = authority_lifecycle();
    let (parent, child) = authority_capabilities();

    let mut output = String::from(
        "# ActiveChain authority vector\n\
# Generated by: cargo run --locked --quiet -p activechain-vector-generator -- authority-v1\n\
# Transcripts: P-001/P-002/P-020/P-022 draft 0.1\n\
\n\
vector=authority-v1\n\
commitment_domain=canonical-value (0x0001)\n\
\n",
    );
    output.push_str(&encoded_value("authenticator", &authenticator));
    output.push('\n');
    output.push_str(&encoded_value("created_principal", &created));
    output.push('\n');
    output.push_str(&encoded_value("rotated_principal", &rotated));
    output.push('\n');
    output.push_str(&encoded_value("recovery_pending_principal", &pending));
    output.push('\n');
    output.push_str(&encoded_value("recovery_request", &recovery_request));
    output.push('\n');
    output.push_str(&encoded_value("parent_capability", &parent));
    output.push('\n');
    output.push_str(&encoded_value("child_capability", &child));
    output.push_str("\nattenuation_result=permit\n");
    output
}

fn apl_values() -> (PolicySet, PolicyRequest, PolicyDecision) {
    let actor = ActorBinding::Principal(identifier_principal(0x10));
    let action = identifier_action(0x20);
    let resource = ObjectId::new(repeated_digest(0x30));
    let purpose = repeated_digest(0x40);
    let credential_schema = repeated_digest(0x50);
    let capability_id = identifier_capability(0x60);
    let approval_role = repeated_digest(0x70);

    let policy = PolicySet::new(
        APL_LANGUAGE_VERSION,
        vec![
            PolicyRule::new(
                PolicyEffect::Permit,
                vec![
                    PolicyPredicate::ActorIs(actor),
                    PolicyPredicate::ActionIs(action),
                    PolicyPredicate::ResourceMatches(ResourceSelector::exact(resource)),
                    PolicyPredicate::ValueAtMost(1_000),
                    PolicyPredicate::HeightAtLeast(40),
                    PolicyPredicate::HasCredentialSchema(credential_schema),
                    PolicyPredicate::HasCapability(capability_id),
                    PolicyPredicate::ApprovalCountAtLeast { role: approval_role, minimum: 2 },
                    PolicyPredicate::FreezeStateIs(FreezeState::Active),
                    PolicyPredicate::DeclaredPurposeIs(purpose),
                ],
                vec![
                    PolicyObligation::DecrementCapabilityBudget { capability_id, amount: 500 },
                    PolicyObligation::ConsumeCapability(capability_id),
                    PolicyObligation::EmitAuditCommitment(repeated_digest(0x80)),
                    PolicyObligation::RequireApproval { role: approval_role, minimum: 2 },
                ],
            )
            .expect("APL vector permit rule is valid"),
            PolicyRule::new(
                PolicyEffect::Permit,
                vec![PolicyPredicate::ValueAtLeast(100), PolicyPredicate::HeightAtMost(60)],
                vec![
                    PolicyObligation::DelaySettlementUntil(55),
                    PolicyObligation::RestrictOutputDisclosure(repeated_digest(0x90)),
                ],
            )
            .expect("APL vector secondary permit rule is valid"),
            PolicyRule::new(
                PolicyEffect::Forbid,
                vec![PolicyPredicate::FreezeStateIs(FreezeState::Frozen)],
                vec![],
            )
            .expect("APL vector forbid rule is valid"),
        ],
    )
    .expect("APL vector policy is bounded");

    let request = PolicyRequest::new(PolicyRequestFields {
        actor,
        action,
        resource,
        height: 50,
        value: 500,
        freeze_state: FreezeState::Active,
        declared_purpose: Some(purpose),
        credential_schemas: vec![credential_schema],
        capabilities: vec![capability_id],
        approvals: vec![ApprovalFact::new(approval_role, 2).expect("non-zero approval count")],
    })
    .expect("APL vector request facts are canonical");

    let decision = evaluate(&policy, &request);
    assert_eq!(decision.result(), DecisionResult::Permit);
    assert_eq!(decision.matched_permit_rules(), 2);
    assert_eq!(decision.matched_forbid_rules(), 0);
    assert_eq!(decision.steps_used(), 16);
    assert_eq!(decision.obligations().len(), 6);
    (policy, request, decision)
}

fn render_apl_v1() -> String {
    let (policy, request, decision) = apl_values();
    let mut output = String::from(
        "# ActiveChain APL vector\n\
# Generated by: cargo run --locked --quiet -p activechain-vector-generator -- apl-v1\n\
# Transcripts: P-001/P-023 draft 0.1\n\
\n\
vector=apl-v1\n\
commitment_domain=canonical-value (0x0001)\n\
actor=Principal(10 repeated 48 times)\n\
action=20 repeated 48 times\n\
resource=30 repeated 48 times\n\
height=50\n\
value=500\n\
decision=Permit\n\
matched_permit_rules=2\n\
matched_forbid_rules=0\n\
steps_used=16\n\
obligation_count=6\n\
\n",
    );
    output.push_str(&encoded_value("policy", &policy));
    output.push('\n');
    output.push_str(&encoded_value("request", &request));
    output.push('\n');
    output.push_str(&encoded_value("decision", &decision));
    output
}

fn render_apl_truth_table() -> String {
    let mut output = String::new();
    for (has_permit, has_forbid) in [(false, false), (false, true), (true, false), (true, true)] {
        let result = match combine_effects(has_permit, has_forbid) {
            DecisionResult::Deny => "Deny",
            DecisionResult::Permit => "Permit",
        };
        output.push_str(if has_permit { "true" } else { "false" });
        output.push(',');
        output.push_str(if has_forbid { "true" } else { "false" });
        output.push(',');
        output.push_str(result);
        output.push('\n');
    }
    output
}

fn object_transition_values() -> (
    Object,
    AccessManifest,
    ObjectState,
    TransferTransaction,
    TransitionReceipt,
    Object,
    ObjectState,
) {
    let object_id = ObjectId::new(repeated_digest(0xa0));
    let actor = ActorBinding::Principal(identifier_principal(0xb1));
    let policy = PolicySet::new(
        APL_LANGUAGE_VERSION,
        vec![
            PolicyRule::new(
                PolicyEffect::Permit,
                vec![
                    PolicyPredicate::ActorIs(actor),
                    PolicyPredicate::ActionIs(TRANSFER_OBJECT_ACTION_ID),
                    PolicyPredicate::ResourceMatches(ResourceSelector::exact(object_id)),
                    PolicyPredicate::FreezeStateIs(FreezeState::Active),
                ],
                vec![],
            )
            .expect("object vector control rule is valid"),
        ],
    )
    .expect("object vector policy is bounded");
    let control_policy_hash =
        commit(DomainTag::CANONICAL_VALUE, &policy).expect("object vector control policy encodes");
    let object = Object::new(ObjectFields {
        object_id,
        object_version: 7,
        type_id: repeated_digest(0xa1),
        owner: ObjectOwner::Principal(identifier_principal(0xb1)),
        control_policy_hash,
        use_policy_hash: repeated_digest(0xa2),
        disclosure_policy_hash: repeated_digest(0xa3),
        upgrade_policy_hash: repeated_digest(0xa4),
        package_id: None,
        value_root: repeated_digest(0xa5),
        public_value: Some(b"activechain-object-v1".to_vec()),
        lease_expiry_epoch: 100,
        storage_deposit: 5_000,
        flags: ObjectFlags::TRANSFERABLE.union(ObjectFlags::LINEAR),
    })
    .expect("object vector value is canonical");
    let input = ObjectVersionRef::new(object_id, 7);
    let manifest = AccessManifest::new(AccessManifestFields {
        exact_reads: vec![],
        exact_writes: vec![input],
        immutable_reads: vec![],
        creation_namespaces: vec![],
        maximum_created_objects: 0,
        maximum_dynamic_reads: 0,
        dynamic_read_policy: None,
    })
    .expect("object vector manifest is canonical");
    let request = PolicyRequest::new(PolicyRequestFields {
        actor,
        action: TRANSFER_OBJECT_ACTION_ID,
        resource: object_id,
        height: 50,
        value: 0,
        freeze_state: FreezeState::Active,
        declared_purpose: None,
        credential_schemas: vec![],
        capabilities: vec![],
        approvals: vec![],
    })
    .expect("object vector request is canonical");
    let transaction = TransferTransaction::new(
        50,
        manifest.clone(),
        vec![TransferCommand::new(
            input,
            ObjectOwner::Shielded(repeated_digest(0xb0)),
            policy,
            request,
        )],
    )
    .expect("object vector transaction is canonical");
    let pre_state = ObjectState::new(vec![object.clone()]).expect("object vector state is ordered");
    let output = apply_transfer_transaction(&pre_state, &transaction)
        .expect("object vector transition is structurally valid");
    assert_eq!(output.receipt().result(), ReceiptResult::Success);
    assert_eq!(output.receipt().objects_updated(), 1);
    assert_eq!(output.receipt().policy_steps(), 5);
    let post_object =
        output.state().find(object_id).expect("transition preserves object identity").clone();
    assert_eq!(post_object.object_version(), 8);
    (
        object,
        manifest,
        pre_state,
        transaction,
        output.receipt(),
        post_object,
        output.state().clone(),
    )
}

fn render_object_transition_v1() -> String {
    let (object, manifest, pre_state, transaction, receipt, post_object, post_state) =
        object_transition_values();
    let mut output = String::from(
        "# ActiveChain object transition vector\n\
# Generated by: cargo run --locked --quiet -p activechain-vector-generator -- object-transition-v1\n\
# Transcripts: P-001/P-010/P-023/P-030 draft\n\
\n\
vector=object-transition-v1\n\
commitment_domain=canonical-value (0x0001)\n\
object_id=a0 repeated 48 times\n\
object_version_before=7\n\
object_version_after=8\n\
new_owner=Shielded(b0 repeated 48 times)\n\
receipt=Success\n\
objects_updated=1\n\
policy_steps=5\n\
\n",
    );
    output.push_str(&encoded_value("object_before", &object));
    output.push('\n');
    output.push_str(&encoded_value("access_manifest", &manifest));
    output.push('\n');
    output.push_str(&encoded_value("pre_state", &pre_state));
    output.push('\n');
    output.push_str(&encoded_value("transfer_transaction", &transaction));
    output.push('\n');
    output.push_str(&encoded_value("transition_receipt", &receipt));
    output.push('\n');
    output.push_str(&encoded_value("object_after", &post_object));
    output.push('\n');
    output.push_str(&encoded_value("post_state", &post_state));
    output
}

fn model_object(version: u64) -> Object {
    Object::new(ObjectFields {
        object_id: ObjectId::new(repeated_digest(0xc0)),
        object_version: version,
        type_id: repeated_digest(0xc1),
        owner: ObjectOwner::Shared,
        control_policy_hash: Digest384::ZERO,
        use_policy_hash: Digest384::ZERO,
        disclosure_policy_hash: Digest384::ZERO,
        upgrade_policy_hash: Digest384::ZERO,
        package_id: None,
        value_root: Digest384::ZERO,
        public_value: None,
        lease_expiry_epoch: 0,
        storage_deposit: 0,
        flags: ObjectFlags::TRANSFERABLE,
    })
    .expect("model object is canonical")
}

fn render_object_model_table() -> String {
    let mut output = String::new();
    for (version, expected_version, authorized) in
        [(0, 0, true), (7, 6, true), (u64::MAX, u64::MAX, true), (7, 7, false)]
    {
        let result = if !authorized {
            String::from("AuthorizationDenied")
        } else {
            let object = model_object(version);
            match transfer_object(
                &object,
                ObjectVersionRef::new(object.object_id(), expected_version),
                ObjectOwner::Shielded(repeated_digest(0xc2)),
            ) {
                Ok(updated) => format!("Success({})", updated.object_version()),
                Err(ObjectTransitionError::StaleObjectVersion { .. }) => {
                    String::from("StaleObjectVersion")
                }
                Err(ObjectTransitionError::VersionExhausted) => String::from("VersionExhausted"),
                other => panic!("unexpected object model result: {other:?}"),
            }
        };
        output.push_str(&format!("{version},{expected_version},{authorized},{result}\n"));
    }
    output
}

fn main() {
    let vector = std::env::args().nth(1);
    match vector.as_deref().unwrap_or("principal-v1") {
        "principal-v1" => print!("{}", render_principal_v1()),
        "authority-v1" => print!("{}", render_authority_v1()),
        "apl-v1" => print!("{}", render_apl_v1()),
        "apl-truth-table" => print!("{}", render_apl_truth_table()),
        "object-transition-v1" => print!("{}", render_object_transition_v1()),
        "object-model-table" => print!("{}", render_object_model_table()),
        unknown => {
            eprintln!(
                "unknown vector {unknown}; expected principal-v1, authority-v1, apl-v1, or \
                 apl-truth-table, object-transition-v1, or object-model-table"
            );
            std::process::exit(2);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{
        render_apl_truth_table, render_apl_v1, render_authority_v1, render_object_model_table,
        render_object_transition_v1, render_principal_v1,
    };

    #[test]
    fn generated_principal_vector_is_frozen() {
        let published = include_str!("../../../testing/vectors/canonical/principal-v1.txt");
        assert_eq!(render_principal_v1(), published);
    }

    #[test]
    fn generated_authority_vector_is_frozen() {
        let published = include_str!("../../../testing/vectors/authority/authority-v1.txt");
        assert_eq!(render_authority_v1(), published);
    }

    #[test]
    fn generated_apl_vector_is_frozen() {
        let published = include_str!("../../../testing/vectors/policy/apl-v1.txt");
        assert_eq!(render_apl_v1(), published);
    }

    #[test]
    fn rust_effect_table_matches_the_frozen_lean_table() {
        let published = include_str!("../../../testing/vectors/policy/apl-truth-table.txt");
        assert_eq!(render_apl_truth_table(), published);
    }

    #[test]
    fn generated_object_transition_vector_is_frozen() {
        let published = include_str!("../../../testing/vectors/object/object-transition-v1.txt");
        assert_eq!(render_object_transition_v1(), published);
    }

    #[test]
    fn rust_object_table_matches_the_frozen_lean_table() {
        let published = include_str!("../../../testing/vectors/object/object-model-table.txt");
        assert_eq!(render_object_model_table(), published);
    }
}
