//! Generates the frozen development vectors from typed protocol values.

use activechain_canonical_codec::{encode_body, encode_envelope};
use activechain_protocol_commitment::{DomainTag, commit};
use activechain_protocol_types::{Digest384, FreezeState, Principal, PrincipalId, PrincipalKind};

fn repeated_digest(byte: u8) -> Digest384 {
    Digest384::new([byte; 48])
}

fn principal_v1() -> Principal {
    Principal::new(
        PrincipalId::new(repeated_digest(0x11)),
        PrincipalKind::Agent,
        repeated_digest(0x22),
        repeated_digest(0x33),
        repeated_digest(0x44),
        7,
        FreezeState::Active,
        repeated_digest(0x55),
        1_000,
        42,
        43,
    )
    .expect("the source vector must satisfy the Principal v1 schema")
}

fn hexadecimal(bytes: &[u8]) -> String {
    const DIGITS: &[u8; 16] = b"0123456789abcdef";

    let mut output = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        output.push(char::from(DIGITS[usize::from(byte >> 4)]));
        output.push(char::from(DIGITS[usize::from(byte & 0x0f)]));
    }
    output
}

fn render_principal_v1() -> String {
    let principal = principal_v1();
    let body = encode_body(&principal).expect("Principal v1 body must fit its declared bound");
    let envelope =
        encode_envelope(&principal).expect("Principal v1 envelope must fit its declared bound");
    let commitment = commit(DomainTag::CANONICAL_VALUE, &principal)
        .expect("Principal v1 commitment input must encode");

    format!(
        "# ActiveChain canonical vector\n\
# Generated by: cargo run --locked --quiet -p activechain-vector-generator\n\
# Transcript: P-001 draft 0.1\n\
\n\
vector=principal-v1\n\
type_tag=0x{:04x}\n\
schema_version={}\n\
\n\
principal_id=11 repeated 48 times\n\
principal_kind=Agent (4)\n\
controller_policy_hash=22 repeated 48 times\n\
recovery_policy_hash=33 repeated 48 times\n\
authenticator_set_root=44 repeated 48 times\n\
sequence=7\n\
freeze_state=Active (0)\n\
metadata_commitment=55 repeated 48 times\n\
anchor_deposit=1000\n\
created_at=42\n\
last_updated_at=43\n\
\n\
body_length={}\n\
body_hex={}\n\
envelope_hex={}\n\
commitment_domain=canonical-value (0x0001)\n\
canonical_value_commitment_hex={}\n",
        Principal::TYPE_TAG,
        Principal::SCHEMA_VERSION,
        body.len(),
        hexadecimal(&body),
        hexadecimal(&envelope),
        hexadecimal(commitment.as_bytes())
    )
}

fn main() {
    print!("{}", render_principal_v1());
}

#[cfg(test)]
mod tests {
    use super::render_principal_v1;

    #[test]
    fn generated_principal_vector_is_frozen() {
        let published = include_str!("../../../testing/vectors/canonical/principal-v1.txt");
        assert_eq!(render_principal_v1(), published);
    }
}
