#!/usr/bin/env bash
set -euo pipefail

archive="${1:?usage: activate-kanalen-release.sh <archive> <checksum> <release-id>}"
checksum="${2:?usage: activate-kanalen-release.sh <archive> <checksum> <release-id>}"
release_id="${3:?usage: activate-kanalen-release.sh <archive> <checksum> <release-id>}"
deployment_root="${ACTIVECHAIN_KANALEN_ROOT:-$HOME/activechain-deploy/kanalen}"
launchctl_bin="${ACTIVECHAIN_LAUNCHCTL:-launchctl}"
plutil_bin="${ACTIVECHAIN_PLUTIL:-plutil}"
docker_bin="${ACTIVECHAIN_DOCKER:-docker}"
release_root="$deployment_root/releases"
release_dir="$release_root/$release_id"
staging_dir=""

cleanup() {
  if [[ -n "$staging_dir" && -d "$staging_dir" ]]; then
    rm -rf "$staging_dir"
  fi
}
trap cleanup EXIT

if [[ ! "$release_id" =~ ^[0-9a-f]{40}$ ]]; then
  echo "release ID must be a full lowercase Git commit: $release_id" >&2
  exit 1
fi
if [[ -L "$archive" || ! -f "$archive" || -L "$checksum" || ! -f "$checksum" ]]; then
  echo "release archive and checksum must be regular, non-symlink files" >&2
  exit 1
fi

expected_digest="$(awk 'NR == 1 { print $1 }' "$checksum")"
actual_digest="$(shasum -a 256 "$archive" | awk '{ print $1 }')"
if [[ ! "$expected_digest" =~ ^[0-9a-f]{64}$ || "$actual_digest" != "$expected_digest" ]]; then
  echo "release archive checksum mismatch" >&2
  exit 1
fi

while IFS= read -r entry; do
  case "$entry" in
    kanalen|kanalen/*) ;;
    *)
      echo "release archive contains an unexpected path: $entry" >&2
      exit 1
      ;;
  esac
  case "/$entry/" in
    */../*|*/./*)
      echo "release archive contains an unsafe path: $entry" >&2
      exit 1
      ;;
  esac
done < <(tar -tzf "$archive")

mkdir -p "$release_root"
if [[ -e "$release_dir" ]]; then
  if [[ ! -f "$release_dir/.archive.sha256" ]] ||
    [[ "$(cat "$release_dir/.archive.sha256")" != "$actual_digest" ]]; then
    echo "release directory already exists with different content: $release_dir" >&2
    exit 1
  fi
else
  staging_dir="$(mktemp -d "$release_root/.${release_id}.XXXXXX")"
  tar -xzf "$archive" -C "$staging_dir"
  if [[ ! -d "$staging_dir/kanalen" ]]; then
    echo "release archive does not contain the kanalen root" >&2
    exit 1
  fi
  printf '%s\n' "$actual_digest" >"$staging_dir/kanalen/.archive.sha256"
  mv "$staging_dir/kanalen" "$release_dir"
  rmdir "$staging_dir"
  staging_dir=""
fi

for binary in validator-node activechain-rpc-node activechain-telemetry-anchor-gateway actum-work-proof-api actum-work-proof-verifier actum-work-proof-trust-bootstrap; do
  if [[ ! -x "$release_dir/bin/$binary" ]]; then
    echo "release is missing executable $binary" >&2
    exit 1
  fi
done
if [[ ! -x "$release_dir/scripts/provision-work-proof-verifier.sh" ]]; then
  echo "release is missing the work-proof provisioning script" >&2
  exit 1
fi
for gateway_file in compose.yml dynamic.yml traefik.yml switch-edge.sh; do
  if [[ ! -f "$release_dir/gateway/$gateway_file" ]]; then
    echo "release is missing gateway/$gateway_file" >&2
    exit 1
  fi
done

candidate_network="$release_dir/network.env"
runtime_network="$deployment_root/network.env"
candidate_chain="$(sed -n 's/^ACTIVECHAIN_CHAIN_ID_HEX=//p' "$candidate_network")"
if [[ -z "$candidate_chain" ]]; then
  echo "candidate release has no chain ID" >&2
  exit 1
fi
if [[ -f "$runtime_network" ]]; then
  runtime_chain="$(sed -n 's/^ACTIVECHAIN_CHAIN_ID_HEX=//p' "$runtime_network")"
  if [[ -z "$runtime_chain" || "$runtime_chain" != "$candidate_chain" ]]; then
    echo "candidate release would substitute the deployed chain ID" >&2
    exit 1
  fi
else
  install -m 0644 "$candidate_network" "$runtime_network"
fi

# The cash treasury owner is regenerated by every state reset and recorded in
# network.env, but launchd cannot read that file. Without it the RPC infers the
# faucet source from "the only cash owner", which stops being true the moment
# the faucet pays anyone, and the node then refuses to start.
cash_owner=$(sed -n 's/^ACTIVECHAIN_CASH_GENESIS_OWNER_HEX=//p' "$runtime_network")
if [[ -n "$cash_owner" ]]; then
  rpc_plist="$release_dir/launchagents/dev.activechain.kanalen.rpc.plist"
  /usr/libexec/PlistBuddy \
    -c "Add :EnvironmentVariables:ACTIVECHAIN_CASH_GENESIS_OWNER_HEX string $cash_owner" \
    "$rpc_plist" 2>/dev/null ||
    /usr/libexec/PlistBuddy \
      -c "Set :EnvironmentVariables:ACTIVECHAIN_CASH_GENESIS_OWNER_HEX $cash_owner" \
      "$rpc_plist"
  "$plutil_bin" -lint "$rpc_plist" >/dev/null
fi

ACTIVECHAIN_KANALEN_ROOT="$deployment_root" \
ACTIVECHAIN_WORK_PROOF_BINARY_DIR="$release_dir/bin" \
  bash "$release_dir/scripts/provision-work-proof-verifier.sh"

if [[ -e "$deployment_root/current" && ! -L "$deployment_root/current" ]]; then
  echo "current release path must be absent or a symlink" >&2
  exit 1
fi
ln -sfn "$release_dir" "$deployment_root/current"
mkdir -p "$HOME/Library/Logs/ActiveChain"

launch_domain="gui/$(id -u)"
for label in \
  dev.activechain.kanalen.validator0 \
  dev.activechain.kanalen.validator1 \
  dev.activechain.kanalen.validator2 \
  dev.activechain.kanalen.rpc \
  dev.activechain.kanalen.anchor \
  dev.activechain.kanalen.work-proof \
  dev.activechain.kanalen.round; do
  plist="$release_dir/launchagents/$label.plist"
  if [[ ! -f "$plist" ]]; then
    echo "release is missing launch agent $label" >&2
    exit 1
  fi
  "$plutil_bin" -lint "$plist" >/dev/null
  "$launchctl_bin" bootout "$launch_domain/$label" 2>/dev/null || true
  "$launchctl_bin" bootstrap "$launch_domain" "$plist"
done

gateway_dir="$deployment_root/gateway"
install -d -m 0755 "$gateway_dir"
install -d -m 0700 "$gateway_dir/letsencrypt"
for gateway_file in compose.yml dynamic.yml traefik.yml; do
  install -m 0644 "$release_dir/gateway/$gateway_file" "$gateway_dir/$gateway_file"
done
install -m 0755 "$release_dir/gateway/switch-edge.sh" "$gateway_dir/switch-edge.sh"
if [[ -f "$release_dir/gateway/README.md" ]]; then
  install -m 0644 "$release_dir/gateway/README.md" "$gateway_dir/README.md"
fi
if [[ -f "$release_dir/gateway/kanalen.Caddyfile" ]]; then
  install -m 0644 "$release_dir/gateway/kanalen.Caddyfile" "$gateway_dir/kanalen.Caddyfile"
fi
"$docker_bin" compose -f "$gateway_dir/compose.yml" config >/dev/null
"$docker_bin" compose -f "$gateway_dir/compose.yml" up -d

echo "activated Kanalen release $release_id"
