#ifndef ACTIVECHAIN_WALLET_H
#define ACTIVECHAIN_WALLET_H

/* Generated by activechain-apple-distribution. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define ACTIVECHAIN_WALLET_OK 0

#define ACTIVECHAIN_WALLET_NULL_POINTER 1

#define ACTIVECHAIN_WALLET_TOO_LARGE 2

#define ACTIVECHAIN_WALLET_MALFORMED 3

#define ACTIVECHAIN_WALLET_INSUFFICIENT_FUNDS 4

#define ACTIVECHAIN_WALLET_BUFFER_TOO_SMALL 5

#define ACTIVECHAIN_WALLET_CALLBACK_FAILED 6

#define ACTIVECHAIN_WALLET_INVALID_SIGNATURE 7

typedef uint32_t (*activechain_wallet_sign_callback)(
    void *context,
    const uint8_t *payload,
    uint32_t payload_len,
    uint8_t *signature_out,
    uint32_t signature_len);

typedef uint32_t (*activechain_wallet_submit_callback)(
    void *context,
    const uint8_t *envelope,
    uint32_t envelope_len);


#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the ABI revision consumed by native wallet shells.
 */
uint32_t activechain_wallet_ffi_revision(void);

/**
 * Validates a bounded OpenWallet session tuple without accepting secret material.
 *
 * # Safety
 *
 * `session_id` and `relying_party` must each point to a readable 48-byte buffer for the
 * duration of this call. The function does not retain either pointer.
 */
uint32_t activechain_wallet_session_valid(const uint8_t *session_id,
                                          const uint8_t *relying_party,
                                          uint64_t expires_at,
                                          uint64_t height);

/**
 * Selects distinct payment and fee-reserve Coin Cells from a canonical bounded set.
 *
 * # Safety
 *
 * The caller must provide readable buffers for the declared lengths, a readable 48-byte owner,
 * and writable 48-byte output buffers. No pointer is retained. Oversized input is rejected before
 * the input pointer is materialized.
 */
uint32_t activechain_wallet_select_cells(const uint8_t *cells,
                                         uint32_t cells_len,
                                         const uint8_t *owner,
                                         uint64_t amount_high,
                                         uint64_t amount_low,
                                         uint64_t fee_high,
                                         uint64_t fee_low,
                                         uint8_t *payment_out,
                                         uint8_t *fee_reserve_out);

/**
 * Evaluates the exact wallet-core spending policy without side effects.
 *
 * # Safety
 *
 * `recipient` must point to 48 readable bytes. `allowed_recipient` may be null to express an
 * unpinned policy; otherwise it must point to 48 readable bytes. No pointer is retained.
 */
uint32_t activechain_wallet_policy_allows(uint64_t daily_limit_high,
                                          uint64_t daily_limit_low,
                                          uint64_t max_single_high,
                                          uint64_t max_single_low,
                                          const uint8_t *allowed_recipient,
                                          uint64_t amount_high,
                                          uint64_t amount_low,
                                          const uint8_t *recipient,
                                          uint64_t spent_high,
                                          uint64_t spent_low);

/**
 * Builds the exact canonical request shown for approval and later signed by the secure key.
 *
 * # Safety
 *
 * All identifier inputs must point to readable 48-byte buffers. `required_len` and `intent_out`
 * must be writable. `output` may be null only when `output_capacity` is zero for a size query.
 * No output bytes or intent ID are published unless the complete request fits.
 */
uint32_t activechain_wallet_build_cash_intent(const uint8_t *chain_id,
                                              const uint8_t *signer,
                                              const uint8_t *recipient,
                                              const uint8_t *input,
                                              const uint8_t *fee_reserve,
                                              uint64_t nonce,
                                              const uint8_t *session_id,
                                              uint64_t session_expires_at,
                                              uint64_t amount_high,
                                              uint64_t amount_low,
                                              uint64_t fee_high,
                                              uint64_t fee_low,
                                              uint64_t valid_until,
                                              uint8_t *output,
                                              uint32_t output_capacity,
                                              uint32_t *required_len,
                                              uint8_t *intent_out);

/**
 * Invokes a secure-key callback for one exact canonical request and verifies its result.
 *
 * # Safety
 *
 * `request` and `public_key` must be readable for their fixed lengths. `callback` must obey its
 * declared contract for the duration of the call. `output` may be null only for a zero-capacity
 * size query; `required_len` must be writable. The callback is never retained.
 */
uint32_t activechain_wallet_sign_cash_intent(const uint8_t *request,
                                             uint32_t request_len,
                                             const uint8_t *public_key,
                                             activechain_wallet_sign_callback callback,
                                             void *callback_context,
                                             uint8_t *output,
                                             uint32_t output_capacity,
                                             uint32_t *required_len);

/**
 * Verifies and forwards one exact authorized envelope to a caller-owned transport.
 *
 * # Safety
 *
 * `envelope` and `public_key` must be readable for their declared/fixed lengths. `callback` must
 * obey its contract for the duration of the call. No pointer is retained.
 */
uint32_t activechain_wallet_submit_authorized(const uint8_t *envelope,
                                              uint32_t envelope_len,
                                              const uint8_t *public_key,
                                              activechain_wallet_submit_callback callback,
                                              void *callback_context);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ACTIVECHAIN_WALLET_H */
