#ifndef ACTIVECHAIN_WALLET_H
#define ACTIVECHAIN_WALLET_H

/* Generated by activechain-apple-distribution. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define ACTIVECHAIN_WALLET_OK 0

#define ACTIVECHAIN_WALLET_NULL_POINTER 1

#define ACTIVECHAIN_WALLET_TOO_LARGE 2

#define ACTIVECHAIN_WALLET_MALFORMED 3

#define ACTIVECHAIN_WALLET_INSUFFICIENT_FUNDS 4

#define ACTIVECHAIN_WALLET_BUFFER_TOO_SMALL 5

#define ACTIVECHAIN_WALLET_CALLBACK_FAILED 6

#define ACTIVECHAIN_WALLET_INVALID_SIGNATURE 7

#define ACTIVECHAIN_WALLET_AGENT_REJECTED 8

#define ACTIVECHAIN_WALLET_INVALID_PROOF 9

#define ACTIVECHAIN_WALLET_APPROVAL_MISMATCH 10

#define ACTIVECHAIN_WALLET_OPENWALLET_OFFER 1

#define ACTIVECHAIN_WALLET_OPENWALLET_PRESENTATION_REQUEST 2

#define ACTIVECHAIN_WALLET_OPENWALLET_CONSENT 3

#define ACTIVECHAIN_WALLET_DID_ML_DSA_65 0
#define ACTIVECHAIN_WALLET_DID_ML_DSA_87 1
#define ACTIVECHAIN_WALLET_DID_SLH_DSA_SHAKE_192S 2

typedef uint32_t (*activechain_wallet_sign_callback)(
    void *context,
    const uint8_t *payload,
    uint32_t payload_len,
    uint8_t *signature_out,
    uint32_t signature_len);

typedef uint32_t (*activechain_wallet_submit_callback)(
    void *context,
    const uint8_t *envelope,
    uint32_t envelope_len);


typedef struct ActivechainWalletAgentSummary {
  uint8_t principal[48];
  uint32_t connection;
  uint32_t lifecycle;
  uint32_t capability_count;
  uint64_t budget_limit_high;
  uint64_t budget_limit_low;
  uint64_t budget_spent_high;
  uint64_t budget_spent_low;
  uint64_t expires_at;
  uint64_t revocation_finalized_height;
} ActivechainWalletAgentSummary;

/**
 * Fixed-layout human-review fields decoded from one canonical cash authorization request.
 */
typedef struct ActivechainWalletCashApproval {
  uint8_t chain_id[48];
  uint8_t signer[48];
  uint8_t recipient[48];
  uint8_t fee_reserve[48];
  uint8_t session_id[48];
  uint8_t intent_id[48];
  uint64_t nonce;
  uint64_t session_expires_at;
  uint64_t amount_high;
  uint64_t amount_low;
  uint64_t fee_high;
  uint64_t fee_low;
  uint64_t valid_until;
  uint32_t input_count;
} ActivechainWalletCashApproval;

/**
 * Fixed-layout review fields decoded from one canonical MCP action intent.
 */
typedef struct ActivechainWalletProposalApproval {
  uint8_t request_id[128];
  uint32_t request_id_len;
  uint8_t chain_id[128];
  uint32_t chain_id_len;
  uint8_t wallet_id[128];
  uint32_t wallet_id_len;
  uint8_t request_nonce[128];
  uint32_t request_nonce_len;
  uint8_t agent_principal[48];
  uint8_t capability_id[48];
  uint8_t resource[48];
  uint8_t recipient[48];
  uint8_t replay_domain[48];
  uint8_t intent_commitment[48];
  uint8_t proposal_id[48];
  uint32_t action;
  uint64_t amount_high;
  uint64_t amount_low;
  uint64_t maximum_fee_high;
  uint64_t maximum_fee_low;
  uint64_t expires_at_height;
} ActivechainWalletProposalApproval;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the ABI revision consumed by native wallet shells.
 */
uint32_t activechain_wallet_ffi_revision(void);

/**
 * Derives the canonical ML-DSA-44 public key for one transient 32-byte seed.
 *
 * # Safety
 *
 * `seed` must point to 32 readable bytes and `public_key_out` to 1,312 writable bytes. Neither
 * pointer is retained.
 */
uint32_t activechain_wallet_mldsa44_public_key(const uint8_t *seed,
                                               uint32_t seed_len,
                                               uint8_t *public_key_out,
                                               uint32_t public_key_len);

/**
 * Signs one bounded payload with a transient ML-DSA-44 seed and verifies the signature before
 * publishing it to the caller.
 *
 * # Safety
 *
 * `seed` must point to 32 readable bytes. A non-empty `payload` must be readable for
 * `payload_len` bytes, and `signature_out` must point to 2,420 writable bytes. No pointer is
 * retained.
 */
uint32_t activechain_wallet_mldsa44_sign(const uint8_t *seed,
                                         uint32_t seed_len,
                                         const uint8_t *payload,
                                         uint32_t payload_len,
                                         uint8_t *signature_out,
                                         uint32_t signature_len);

/**
 * Validates one canonical OpenWallet envelope and returns its protocol commitment.
 *
 * `kind` must be one of the `ACTIVECHAIN_WALLET_OPENWALLET_*` constants. This boundary
 * deliberately accepts canonical ActiveChain envelopes rather than JSON so native transport
 * adapters cannot silently reinterpret a consent or presentation request.
 *
 * # Safety
 *
 * `envelope` must be readable for `envelope_len` bytes and `commitment_out` must point to a
 * writable 48-byte buffer. Neither pointer is retained.
 */
uint32_t activechain_wallet_openwallet_validate(uint32_t kind,
                                                const uint8_t *envelope,
                                                uint32_t envelope_len,
                                                uint8_t *commitment_out);

/**
 * Applies one canonical agent-registry command and returns the complete next registry snapshot.
 *
 * Pass an empty registry buffer to start from the canonical empty registry. The input registry is
 * never modified, and no output bytes are published unless the complete next state fits.
 *
 * # Safety
 *
 * Non-empty inputs must point to readable buffers for their declared lengths. `required_len` must
 * be writable. `output` may be null only when `output_capacity` is zero for a size query. No
 * pointer is retained.
 */
uint32_t activechain_wallet_agent_apply(const uint8_t *registry,
                                        uint32_t registry_len,
                                        const uint8_t *command,
                                        uint32_t command_len,
                                        uint8_t *output,
                                        uint32_t output_capacity,
                                        uint32_t *required_len);

/**
 * Registers one native agent and returns the complete canonical next registry.
 *
 * Capabilities are a contiguous array of `capability_count * 48` bytes and must already be
 * strictly ordered. The label must be non-empty UTF-8.
 *
 * # Safety
 *
 * All non-empty inputs and outputs must point to readable/writable buffers for their declared
 * lengths. Fixed identifiers point to 48 bytes. No pointer is retained.
 */
uint32_t activechain_wallet_agent_register(const uint8_t *registry,
                                           uint32_t registry_len,
                                           const uint8_t *principal,
                                           const uint8_t *label,
                                           uint32_t label_len,
                                           uint32_t connection,
                                           const uint8_t *capabilities,
                                           uint32_t capability_count,
                                           uint64_t budget_limit_high,
                                           uint64_t budget_limit_low,
                                           uint64_t expires_at,
                                           uint8_t *output,
                                           uint32_t output_capacity,
                                           uint32_t *required_len);

/**
 * Creates a non-authorizing agent record that can become active only after exact finality.
 *
 * # Safety
 *
 * Inputs follow `activechain_wallet_agent_register`; `transaction` points to 48 readable bytes.
 */
uint32_t activechain_wallet_agent_register_pending(const uint8_t *registry,
                                                   uint32_t registry_len,
                                                   const uint8_t *principal,
                                                   const uint8_t *label,
                                                   uint32_t label_len,
                                                   uint32_t connection,
                                                   const uint8_t *capabilities,
                                                   uint32_t capability_count,
                                                   uint64_t budget_limit_high,
                                                   uint64_t budget_limit_low,
                                                   uint64_t expires_at,
                                                   const uint8_t *transaction,
                                                   uint8_t *output,
                                                   uint32_t output_capacity,
                                                   uint32_t *required_len);

/**
 * Activates the exact pending enrollment after its transaction is finalized.
 *
 * # Safety
 *
 * Principal and transaction point to 48 readable bytes; registry/output follow
 * `activechain_wallet_agent_apply`.
 */
uint32_t activechain_wallet_agent_finalize_enrollment(const uint8_t *registry,
                                                      uint32_t registry_len,
                                                      const uint8_t *principal,
                                                      const uint8_t *transaction,
                                                      uint64_t finalized_height,
                                                      uint8_t *output,
                                                      uint32_t output_capacity,
                                                      uint32_t *required_len);

/**
 * Pauses or resumes one agent and returns the canonical next registry.
 *
 * # Safety
 *
 * `principal` points to 48 readable bytes; registry and output pointers follow
 * `activechain_wallet_agent_apply`.
 */
uint32_t activechain_wallet_agent_set_paused(const uint8_t *registry,
                                             uint32_t registry_len,
                                             const uint8_t *principal,
                                             uint32_t paused,
                                             uint8_t *output,
                                             uint32_t output_capacity,
                                             uint32_t *required_len);

/**
 * Starts or finalizes an agent revocation and returns the canonical next registry.
 *
 * Pass `finalized_height == 0` to begin revocation; a non-zero height finalizes the same
 * transaction.
 *
 * # Safety
 *
 * Principal and transaction pointers each point to 48 readable bytes; other pointers follow
 * `activechain_wallet_agent_apply`.
 */
uint32_t activechain_wallet_agent_revoke(const uint8_t *registry,
                                         uint32_t registry_len,
                                         const uint8_t *principal,
                                         const uint8_t *transaction,
                                         uint64_t finalized_height,
                                         uint8_t *output,
                                         uint32_t output_capacity,
                                         uint32_t *required_len);

/**
 * Returns the number of agents in a canonical registry.
 *
 * # Safety
 *
 * Registry bytes must be readable and `count_out` writable. No pointer is retained.
 */
uint32_t activechain_wallet_agent_count(const uint8_t *registry,
                                        uint32_t registry_len,
                                        uint32_t *count_out);

/**
 * Returns one agent summary and its UTF-8 label.
 *
 * Label output supports the standard size-query pattern. The summary is not written unless the
 * complete label fits, so callers never observe a partial record.
 *
 * # Safety
 *
 * Registry bytes must be readable, summary and required-length outputs writable, and `label_out`
 * may be null only for a zero-capacity size query.
 */
uint32_t activechain_wallet_agent_summary(const uint8_t *registry,
                                          uint32_t registry_len,
                                          uint32_t index,
                                          struct ActivechainWalletAgentSummary *summary_out,
                                          uint8_t *label_out,
                                          uint32_t label_capacity,
                                          uint32_t *label_required);

/**
 * Validates a bounded OpenWallet session tuple without accepting secret material.
 *
 * # Safety
 *
 * `session_id` and `relying_party` must each point to a readable 48-byte buffer for the
 * duration of this call. The function does not retain either pointer.
 */
uint32_t activechain_wallet_session_valid(const uint8_t *session_id,
                                          const uint8_t *relying_party,
                                          uint64_t expires_at,
                                          uint64_t height);

/**
 * Verifies a proof-bearing owner-scoped Coin Cell against a trusted chain genesis.
 *
 * # Safety
 * Fixed identifiers must point to readable 48-byte values. Canonical value, proof, and finality
 * buffers must be readable for their declared lengths. No pointer is retained.
 */
uint32_t activechain_wallet_verify_owner_coin_cell_record(const uint8_t *key,
                                                          uint64_t finalized_height,
                                                          const uint8_t *value,
                                                          uint32_t value_len,
                                                          const uint8_t *proof,
                                                          uint32_t proof_len,
                                                          const uint8_t *finality,
                                                          uint32_t finality_len,
                                                          const uint8_t *owner,
                                                          const uint8_t *trusted_genesis);

/** Verifies a proof-bearing NFT series (kind 12) or token registry (kind 13). */
uint32_t activechain_wallet_verify_nft_state_record(uint32_t query_kind,
                                                    const uint8_t *key,
                                                    uint64_t finalized_height,
                                                    const uint8_t *value,
                                                    uint32_t value_len,
                                                    const uint8_t *proof,
                                                    uint32_t proof_len,
                                                    const uint8_t *finality,
                                                    uint32_t finality_len,
                                                    const uint8_t *trusted_genesis);

/**
 * Selects distinct payment and fee-reserve Coin Cells from a canonical bounded set.
 *
 * # Safety
 *
 * The caller must provide readable buffers for the declared lengths, a readable 48-byte owner,
 * and writable 48-byte output buffers. No pointer is retained. Oversized input is rejected before
 * the input pointer is materialized.
 */
uint32_t activechain_wallet_select_cells(const uint8_t *cells,
                                         uint32_t cells_len,
                                         const uint8_t *owner,
                                         uint64_t amount_high,
                                         uint64_t amount_low,
                                         uint64_t fee_high,
                                         uint64_t fee_low,
                                         uint8_t *payment_out,
                                         uint8_t *fee_reserve_out);

/**
 * Selects payment and fee-reserve cells from an explicit fungible asset set.
 *
 * # Safety
 * All pointers must reference buffers valid for their declared lengths; output buffers must be
 * writable for 48 bytes. No pointer is retained.
 */
uint32_t activechain_wallet_select_fungible_cells(const uint8_t *cells,
                                                  uint32_t cells_len,
                                                  const uint8_t *owner,
                                                  uint64_t amount_high,
                                                  uint64_t amount_low,
                                                  uint64_t fee_high,
                                                  uint64_t fee_low,
                                                  uint8_t *payment_out,
                                                  uint8_t *fee_reserve_out);

/**
 * Evaluates the exact wallet-core spending policy without side effects.
 *
 * # Safety
 *
 * `recipient` must point to 48 readable bytes. `allowed_recipient` may be null to express an
 * unpinned policy; otherwise it must point to 48 readable bytes. No pointer is retained.
 */
uint32_t activechain_wallet_policy_allows(uint64_t daily_limit_high,
                                          uint64_t daily_limit_low,
                                          uint64_t max_single_high,
                                          uint64_t max_single_low,
                                          const uint8_t *allowed_recipient,
                                          uint64_t amount_high,
                                          uint64_t amount_low,
                                          const uint8_t *recipient,
                                          uint64_t spent_high,
                                          uint64_t spent_low);

/**
 * Builds the exact canonical request shown for approval and later signed by the secure key.
 *
 * # Safety
 *
 * All identifier inputs must point to readable 48-byte buffers. `required_len` and `intent_out`
 * must be writable. `output` may be null only when `output_capacity` is zero for a size query.
 * No output bytes or intent ID are published unless the complete request fits.
 */
uint32_t activechain_wallet_build_cash_intent(const uint8_t *chain_id,
                                              const uint8_t *signer,
                                              const uint8_t *recipient,
                                              const uint8_t *input,
                                              const uint8_t *fee_reserve,
                                              uint64_t nonce,
                                              const uint8_t *session_id,
                                              uint64_t session_expires_at,
                                              uint64_t amount_high,
                                              uint64_t amount_low,
                                              uint64_t fee_high,
                                              uint64_t fee_low,
                                              uint64_t valid_until,
                                              uint8_t *output,
                                              uint32_t output_capacity,
                                              uint32_t *required_len,
                                              uint8_t *intent_out);

/**
 * Builds a cash authorization whose signature binds an exact faucet settlement reference.
 *
 * # Safety
 *
 * All identifier inputs, including `settlement_reference`, must point to readable 48-byte
 * buffers. Output pointer requirements match [`activechain_wallet_build_cash_intent`].
 */
uint32_t activechain_wallet_build_faucet_cash_intent(const uint8_t *chain_id,
                                                     const uint8_t *signer,
                                                     const uint8_t *recipient,
                                                     const uint8_t *input,
                                                     const uint8_t *fee_reserve,
                                                     uint64_t nonce,
                                                     const uint8_t *session_id,
                                                     uint64_t session_expires_at,
                                                     const uint8_t *settlement_reference,
                                                     uint64_t amount_high,
                                                     uint64_t amount_low,
                                                     uint64_t fee_high,
                                                     uint64_t fee_low,
                                                     uint64_t valid_until,
                                                     uint8_t *output,
                                                     uint32_t output_capacity,
                                                     uint32_t *required_len,
                                                     uint8_t *intent_out);

/**
 * Decodes the exact canonical cash request into fixed human-review fields.
 *
 * # Safety
 * `request` must be readable for `request_len` bytes and `approval_out` must be writable. No
 * pointer is retained and the output is published only after strict canonical decoding succeeds.
 */
uint32_t activechain_wallet_cash_approval(const uint8_t *request,
                                          uint32_t request_len,
                                          struct ActivechainWalletCashApproval *approval_out);

/**
 * Strictly decodes one canonical MCP action intent into fields suitable for native review.
 *
 * The current finalized height is checked here so a stale intent can never reach a platform
 * authentication prompt. Display fields are reconstructed exclusively from canonical bytes.
 *
 * # Safety
 * `intent` must be readable for `intent_len`; `approval_out` must be writable.
 */
uint32_t activechain_wallet_proposal_approval(const uint8_t *intent,
                                              uint32_t intent_len,
                                              uint64_t current_finalized_height,
                                              struct ActivechainWalletProposalApproval *approval_out);

/**
 * Signs one reviewed canonical DID lifecycle operation through caller-owned native custody.
 *
 * The callback receives only the exact chain-genesis-bound signing payload. The returned
 * suite-exact signature is independently verified before the authorization envelope is released.
 * No secret key bytes cross this boundary.
 *
 * # Safety
 * Inputs must be readable for their declared/fixed lengths and outputs must be writable.
 */
uint32_t activechain_wallet_authorize_did_operation(
    const uint8_t *operation,
    uint32_t operation_len,
    const uint8_t *chain_genesis,
    const uint8_t *approved_commitment,
    const uint8_t *authorizer,
    uint32_t suite,
    const uint8_t *public_key,
    uint32_t public_key_len,
    activechain_wallet_sign_callback callback,
    void *callback_context,
    uint8_t *output,
    uint32_t output_capacity,
    uint32_t *required_len);

/**
 * Signs exactly one reviewed canonical MCP action intent through caller-owned native custody.
 *
 * # Safety
 * Input pointers must be readable for their declared/fixed lengths; outputs must be writable.
 * The callback is invoked only after strict decoding, expiry validation, and commitment matching.
 */
uint32_t activechain_wallet_sign_proposal_intent(const uint8_t *intent,
                                                 uint32_t intent_len,
                                                 uint64_t current_finalized_height,
                                                 const uint8_t *approved_commitment,
                                                 const uint8_t *public_key,
                                                 activechain_wallet_sign_callback callback,
                                                 void *callback_context,
                                                 uint8_t *output,
                                                 uint32_t output_capacity,
                                                 uint32_t *required_len);

/**
 * Verifies and forwards one unexpired, exactly authorized MCP action envelope.
 *
 * # Safety
 * `envelope` must be readable for `envelope_len`; the callback must obey its contract.
 */
uint32_t activechain_wallet_submit_authorized_proposal(const uint8_t *envelope,
                                                       uint32_t envelope_len,
                                                       uint64_t current_finalized_height,
                                                       activechain_wallet_submit_callback callback,
                                                       void *callback_context);

/**
 * Builds a canonical asset-bound transfer envelope with size-query support.
 *
 * # Safety
 * All input pointers must reference readable buffers and `required_len` must be writable;
 * `output` must be writable for `output_capacity` bytes.
 */
uint32_t activechain_wallet_build_fungible_transfer(const uint8_t *cells,
                                                    uint32_t cells_len,
                                                    const uint8_t *asset,
                                                    const uint8_t *sender,
                                                    const uint8_t *recipient,
                                                    const uint8_t *input_ids,
                                                    uint16_t input_count,
                                                    uint64_t amount_high,
                                                    uint64_t amount_low,
                                                    uint8_t *output,
                                                    uint32_t output_capacity,
                                                    uint32_t *required_len);

/**
 * Invokes a secure-key callback for one exact canonical request and verifies its result.
 *
 * # Safety
 *
 * `request`, the 48-byte `approved_intent`, and `public_key` must be readable for their declared
 * or fixed lengths. The approved intent must be the commitment returned with the human-reviewed
 * summary. `callback` must obey its declared contract for the duration of the call. `output` may
 * be null only for a zero-capacity size query; `required_len` must be writable. The callback is
 * never retained.
 */
uint32_t activechain_wallet_sign_cash_intent(const uint8_t *request,
                                             uint32_t request_len,
                                             const uint8_t *approved_intent,
                                             const uint8_t *public_key,
                                             activechain_wallet_sign_callback callback,
                                             void *callback_context,
                                             uint8_t *output,
                                             uint32_t output_capacity,
                                             uint32_t *required_len);

/**
 * Verifies and forwards one exact authorized envelope to a caller-owned transport.
 *
 * # Safety
 *
 * `envelope` and `public_key` must be readable for their declared/fixed lengths. `callback` must
 * obey its contract for the duration of the call. No pointer is retained.
 */
uint32_t activechain_wallet_submit_authorized(const uint8_t *envelope,
                                              uint32_t envelope_len,
                                              const uint8_t *public_key,
                                              activechain_wallet_submit_callback callback,
                                              void *callback_context);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ACTIVECHAIN_WALLET_H */
