//! Renders a plan into the files a deployment consists of.
//!
//! Pure, like the compiler: paths in, text out, no filesystem. Writing them is
//! [`crate::apply`]'s job. Keeping the two apart means the exact bytes a
//! deployment will contain can be reviewed, diffed, and tested without a host.
//!
//! Every value here comes from the plan. Nothing is templated by hand, which is
//! the point: the network name, ports, and paths were previously literal in
//! seven launch agents and an environment file, and a second network could not
//! exist without editing all of them.

use crate::NetworkPlan;

/// The complete file content of a deployment, before anything is written.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Materialization {
    /// Relative to the deployment root, in creation order.
    pub directories: Vec<String>,
    /// Relative path and contents.
    pub files: Vec<(String, String)>,
    /// Launch agents, by label, destined for the user's LaunchAgents directory.
    pub launch_agents: Vec<(String, String)>,
}

impl Materialization {
    #[must_use]
    pub fn file(&self, path: &str) -> Option<&str> {
        self.files.iter().find(|(name, _)| name == path).map(|(_, body)| body.as_str())
    }

    #[must_use]
    pub fn launch_agent(&self, label: &str) -> Option<&str> {
        self.launch_agents.iter().find(|(name, _)| name == label).map(|(_, body)| body.as_str())
    }
}

/// Renders every file a plan implies.
///
/// `home` is the absolute home directory the deployment lives under; launch
/// agents cannot use `$HOME` because launchd does not expand it.
#[must_use]
pub fn materialize(plan: &NetworkPlan, home: &str) -> Materialization {
    let root = format!("{home}/activechain-deploy/{}", plan.name);
    // chain/keys is deliberately absent: genesis-tool creates it, and refuses
    // if it already exists, so that it can never write a validator key into a
    // directory that might already hold one.
    let directories = ["chain", "rpc", "logs", "releases", "gateway"]
        .iter()
        .map(|part| format!("{root}/{part}"))
        .collect();

    let files = vec![("network.env".to_owned(), network_env(plan))];

    let mut launch_agents =
        vec![(format!("dev.activechain.{}.rpc", plan.name), rpc_agent(plan, &root))];
    for (index, port) in plan.ports.validators.iter().enumerate() {
        launch_agents.push((
            format!("dev.activechain.{}.validator{index}", plan.name),
            validator_agent(plan, &root, index, *port),
        ));
    }
    launch_agents.push((format!("dev.activechain.{}.round", plan.name), round_agent(plan, &root)));

    Materialization { directories, files, launch_agents }
}

/// The runtime manifest. The genesis commitment and treasury owner are appended
/// by the state reset once keys exist, so they are deliberately absent here:
/// writing placeholders would let a node start against values nobody generated.
fn network_env(plan: &NetworkPlan) -> String {
    let chain_id: String =
        plan.chain_id.as_bytes().iter().map(|byte| format!("{byte:02x}")).collect();
    format!(
        "# Generated by activechain-network-plan. Do not edit by hand.\n\
         # Chain id is derived: SHAKE256-384(\"ACTIVECHAIN-CHAIN-ID-V1\" || domain).\n\
         ACTIVECHAIN_CHAIN_ID_HEX={chain_id}\n\
         ACTIVECHAIN_NETWORK_DOMAIN={domain}\n\
         ACTIVECHAIN_RPC_DOMAIN={rpc}\n\
         # ACTIVECHAIN_GENESIS_COMMITMENT_HEX and ACTIVECHAIN_CASH_GENESIS_OWNER_HEX\n\
         # are appended by the state reset, once the keys they commit to exist.\n\
         ACTIVECHAIN_CASH_GENESIS_SUPPLY={supply}\n\
         ACTIVECHAIN_CASH_SECURITY_RESERVE={reserve}\n\
         ACTIVECHAIN_CASH_TREASURY_CELLS={cells}\n\
         ACTIVECHAIN_FAUCET_CELLS_PER_GRANT={per_grant}\n",
        domain = plan.domain,
        rpc = plan.rpc_hostname,
        supply = plan.genesis_supply,
        reserve = plan.security_reserve,
        cells = plan.treasury_cells,
        per_grant = plan.cells_per_grant,
    )
}

fn rpc_agent(plan: &NetworkPlan, root: &str) -> String {
    let label = format!("dev.activechain.{}.rpc", plan.name);
    plist(
        &label,
        &[
            format!("{root}/current/bin/activechain-rpc-node"),
            format!("{root}/rpc/rpc-index.snapshot"),
            format!("0.0.0.0:{}", plan.ports.rpc),
        ],
        &[
            ("ACTIVECHAIN_WALLET_INGRESS_SNAPSHOT", format!("{root}/chain/cash-ledger.snapshot")),
            ("ACTIVECHAIN_TRANSFER_SNAPSHOT", format!("{root}/rpc/transfers.snapshot")),
            ("ACTIVECHAIN_TRANSFER_ENABLED", "true".to_owned()),
            ("ACTIVECHAIN_TRANSFER_MAX_PENDING_COUNT", "16".to_owned()),
            ("ACTIVECHAIN_TRANSFER_MAX_PENDING_BYTES", "786432".to_owned()),
            ("ACTIVECHAIN_TRANSFER_MAX_RETAINED_RECORDS", "1024".to_owned()),
            ("ACTIVECHAIN_TRANSFER_RETENTION_SECONDS", "604800".to_owned()),
            ("ACTIVECHAIN_TRANSFER_SIGNER_WINDOW", "60".to_owned()),
            ("ACTIVECHAIN_TRANSFER_SIGNER_LIMIT", "4".to_owned()),
            ("ACTIVECHAIN_TRANSFER_GLOBAL_WINDOW", "60".to_owned()),
            ("ACTIVECHAIN_TRANSFER_GLOBAL_LIMIT", "32".to_owned()),
            ("ACTIVECHAIN_TRANSFER_FINALITY_ARCHIVE_DIR", format!("{root}/chain")),
            ("ACTIVECHAIN_FAUCET_SNAPSHOT", format!("{root}/rpc/faucet.snapshot")),
            (
                "ACTIVECHAIN_FAUCET_SETTLEMENT_JOURNAL",
                format!("{root}/rpc/faucet-settlement.journal"),
            ),
            ("ACTIVECHAIN_FAUCET_ACTION_SPOOL", format!("{root}/chain/cash-action-spool")),
            ("ACTIVECHAIN_FAUCET_FINALITY_ARCHIVE_DIR", format!("{root}/chain")),
            ("ACTIVECHAIN_FAUCET_OPERATOR_SEED", format!("{root}/chain/keys/faucet-operator.seed")),
            ("ACTIVECHAIN_ANCHOR_SNAPSHOT", format!("{root}/rpc/anchors.snapshot")),
        ],
        &format!("{root}/logs/rpc.log"),
    )
}

fn validator_agent(plan: &NetworkPlan, root: &str, index: usize, port: u16) -> String {
    let label = format!("dev.activechain.{}.validator{index}", plan.name);
    plist(
        &label,
        &[
            format!("{root}/current/bin/validator-node"),
            port.to_string(),
            format!("{root}/chain/validator-{index}.snapshot"),
            format!("{root}/chain/genesis.bin"),
            "0".to_owned(),
            index.to_string(),
            format!("--key-file={root}/chain/keys/validator-{index}.key"),
        ],
        &[],
        &format!("{root}/logs/validator-{index}.log"),
    )
}

fn round_agent(plan: &NetworkPlan, root: &str) -> String {
    let label = format!("dev.activechain.{}.round", plan.name);
    let mut body = plist(
        &label,
        &[format!("{root}/current/scripts/run-network-round.sh")],
        &[("ACTIVECHAIN_NETWORK_ROOT", root.to_owned())],
        &format!("{root}/logs/round.log"),
    );
    // The round is periodic rather than resident, so it is scheduled instead of
    // kept alive; a KeepAlive round would respawn continuously.
    body = body.replace(
        "  <key>KeepAlive</key><true/>\n",
        "  <key>StartInterval</key><integer>30</integer>\n",
    );
    body
}

fn plist(label: &str, arguments: &[String], environment: &[(&str, String)], log: &str) -> String {
    let mut out = String::from(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \
         \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n\
         <plist version=\"1.0\"><dict>\n",
    );
    out.push_str(&format!("  <key>Label</key><string>{label}</string>\n"));
    out.push_str("  <key>ProgramArguments</key><array>\n");
    for argument in arguments {
        out.push_str(&format!("    <string>{}</string>\n", escape(argument)));
    }
    out.push_str("  </array>\n");
    if !environment.is_empty() {
        out.push_str("  <key>EnvironmentVariables</key><dict>\n");
        for (key, value) in environment {
            out.push_str(&format!("    <key>{key}</key><string>{}</string>\n", escape(value)));
        }
        out.push_str("  </dict>\n");
    }
    out.push_str("  <key>RunAtLoad</key><true/>\n");
    out.push_str("  <key>KeepAlive</key><true/>\n");
    out.push_str(&format!(
        "  <key>StandardOutPath</key><string>{log}</string>\n\
         \x20 <key>StandardErrorPath</key><string>{log}</string>\n"
    ));
    out.push_str("</dict></plist>\n");
    out
}

/// A path containing XML metacharacters would otherwise produce a plist that
/// `plutil -lint` rejects, or worse, one that parses into something else.
fn escape(value: &str) -> String {
    value.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tests_support::manifest;

    fn rendered(name: &str, port: u16) -> Materialization {
        materialize(&crate::plan(&manifest(name, port)).unwrap(), "/Users/operator")
    }

    /// Rendering must reproduce the layout the live network runs, or planning an
    /// existing deployment would propose something subtly different.
    #[test]
    fn a_rendered_deployment_matches_the_shape_the_live_network_uses() {
        let out = rendered("kanalen", 49_151);
        let rpc = out.launch_agent("dev.activechain.kanalen.rpc").expect("rpc agent");
        assert!(rpc.contains("<string>0.0.0.0:49151</string>"));
        assert!(rpc.contains("/Users/operator/activechain-deploy/kanalen/rpc/rpc-index.snapshot"));
        assert!(rpc.contains("ACTIVECHAIN_FAUCET_SETTLEMENT_JOURNAL"));
        assert!(rpc.contains("ACTIVECHAIN_TRANSFER_SNAPSHOT"));
        assert!(rpc.contains("/Users/operator/activechain-deploy/kanalen/rpc/transfers.snapshot"));

        let validator = out.launch_agent("dev.activechain.kanalen.validator0").expect("validator");
        assert!(validator.contains("<string>49153</string>"));
        assert!(validator.contains("validator-0.snapshot"));

        assert!(out.directories.iter().any(|d| d.ends_with("/chain")));
        assert!(
            !out.directories.iter().any(|d| d.ends_with("/chain/keys")),
            "genesis-tool creates the key directory and refuses a pre-existing one"
        );
        assert!(out.directories.iter().any(|d| d.ends_with("/logs")));
    }

    /// The round is periodic. Keeping it alive would respawn it continuously.
    #[test]
    fn the_round_is_scheduled_rather_than_kept_alive() {
        let out = rendered("kanalen", 49_151);
        let round = out.launch_agent("dev.activechain.kanalen.round").expect("round agent");
        assert!(round.contains("<key>StartInterval</key><integer>30</integer>"));
        assert!(!round.contains("KeepAlive"));
    }

    /// Two networks must share no path, port, or label, or starting the second
    /// one damages the first.
    #[test]
    fn two_rendered_networks_collide_in_nothing() {
        let first = rendered("kanalen", 49_151);
        let second = rendered("kibera", 49_167);

        let labels = |out: &Materialization| {
            out.launch_agents.iter().map(|(label, _)| label.clone()).collect::<Vec<_>>()
        };
        for label in labels(&first) {
            assert!(!labels(&second).contains(&label), "shared launch agent label {label}");
        }
        for directory in &first.directories {
            assert!(!second.directories.contains(directory), "shared directory {directory}");
        }
        assert_ne!(first.file("network.env"), second.file("network.env"));
        assert!(
            second.launch_agent("dev.activechain.kibera.rpc").unwrap().contains("0.0.0.0:49167")
        );
    }

    /// The renderer and the checked-in Kanalen launch agents describe the same
    /// deployment, so they must not drift apart. Two sources of truth for one
    /// thing is how a hand-edited plist and a generated one end up disagreeing
    /// about which port a validator binds.
    ///
    /// This pins agreement on the facts the renderer owns — labels and ports —
    /// against the artifacts the live network actually runs.
    #[test]
    fn the_renderer_agrees_with_the_launch_agents_the_live_network_runs() {
        let mut directory = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        while !directory.join("deploy/kanalen/launchagents").is_dir() {
            assert!(directory.pop(), "could not locate deploy/kanalen/launchagents");
        }
        let agents = directory.join("deploy/kanalen/launchagents");
        let out = rendered("kanalen", 49_151);

        for (label, body) in &out.launch_agents {
            let existing = std::fs::read_to_string(agents.join(format!("{label}.plist")))
                .unwrap_or_else(|_| {
                    panic!("the renderer produces {label} but no checked-in agent matches it")
                });
            assert!(existing.contains(label), "{label} disagrees on its own label");
            for port in ports_in(body) {
                assert!(
                    existing.contains(&port),
                    "{label}: rendered port {port} is not the one the live agent binds"
                );
            }
        }
    }

    /// Every `<string>` that is exactly a port number.
    fn ports_in(plist: &str) -> Vec<String> {
        plist
            .lines()
            .filter_map(|line| line.trim().strip_prefix("<string>"))
            .filter_map(|rest| rest.strip_suffix("</string>"))
            .map(|value| value.rsplit(':').next().unwrap_or(value).to_owned())
            .filter(|value| {
                value.len() == 5
                    && value.starts_with("49")
                    && value.chars().all(|c| c.is_ascii_digit())
            })
            .collect()
    }

    /// A generated environment must not carry values nobody has produced yet.
    /// Placeholders would let a node start against a genesis that does not
    /// exist, which is exactly the class of failure this crate exists to stop.
    #[test]
    fn the_environment_omits_commitments_that_do_not_exist_yet() {
        let out = rendered("kanalen", 49_151);
        let env = out.file("network.env").expect("network.env");
        assert!(env.contains(
            "ACTIVECHAIN_CHAIN_ID_HEX=b12c1c316717e9669cec36f7632a9080702c57a3125d90c72154f8a7298e4f0b095e6cfe944bd2c9f6535b4c927782f1"
        ));
        assert!(env.contains("ACTIVECHAIN_CASH_TREASURY_CELLS=96"));
        assert!(env.contains("ACTIVECHAIN_FAUCET_CELLS_PER_GRANT=2"));
        assert!(
            !env.contains("ACTIVECHAIN_GENESIS_COMMITMENT_HEX="),
            "a genesis commitment must not be invented before the genesis exists"
        );
        assert!(
            !env.contains("ACTIVECHAIN_CASH_GENESIS_OWNER_HEX="),
            "a treasury owner must not be invented before the keys exist"
        );
    }
}
